import re
import os

fixes = [
    ("src/agents/prompt-sections/index.ts", "_AgentPromptMetadata", "AgentPromptMetadata"),
    ("src/analytics/backfill-engine.ts", "_TranscriptEntry", "TranscriptEntry"),
    ("src/analytics/query-engine.ts", "_getMetricsCollector", "getMetricsCollector"),
    ("src/analytics/query-engine.ts", "_aggregators", "aggregators"),
    ("src/analytics/transcript-scanner.ts", "_sep", "sep"),
    ("src/cli/commands/doctor-conflicts.ts", "_PluginConfig", "PluginConfig"),
    ("src/cli/index.ts", "_readFileSync", "readFileSync"),
    ("src/cli/launch.ts", "_quoteShellArg", "quoteShellArg"),
    ("src/cli/launch.ts", "_ClaudeLaunchPolicy", "ClaudeLaunchPolicy"),
    ("src/compatibility/discovery.ts", "_statSync", "statSync"),
    ("src/compatibility/discovery.ts", "_dirname", "dirname"),
    ("src/compatibility/mcp-bridge.ts", "_DiscoveredMcpServer", "DiscoveredMcpServer"),
    ("src/compatibility/permission-adapter.ts", "_ExternalTool", "ExternalTool"),
    ("src/compatibility/permission-adapter.ts", "_PluginPermission", "PluginPermission"),
    ("src/config/loader.ts", "_homedir", "homedir"),
    ("src/config/loader.ts", "_DelegationRoutingConfig", "DelegationRoutingConfig"),
    ("src/features/boulder-state/storage.ts", "_writeFileSync", "writeFileSync"),
    ("src/features/delegation-routing/__tests__/resolver.test.ts", "_ResolveDelegationOptions", "ResolveDelegationOptions"),
    ("src/features/rate-limit-wait/daemon.ts", "_formatTimeUntilReset", "formatTimeUntilReset"),
    ("src/features/rate-limit-wait/daemon.ts", "_BlockedPane", "BlockedPane"),
    ("src/features/task-decomposer/index.ts", "_FileOwnership", "FileOwnership"),
    ("src/hooks/__tests__/bridge-routing.test.ts", "_HookOutput", "HookOutput"),
    ("src/hooks/__tests__/bridge-security.test.ts", "_KNOWN_FIELDS", "KNOWN_FIELDS"),
    ("src/hooks/__tests__/bridge.test.ts", "_HookOutput", "HookOutput"),
    ("src/hooks/__tests__/compaction-concurrency.test.ts", "_writeFileSync", "writeFileSync"),
    ("src/hooks/autopilot/__tests__/state.test.ts", "_writeAutopilotState", "writeAutopilotState"),
    ("src/hooks/autopilot/__tests__/state.test.ts", "_updatePlanning", "updatePlanning"),
    ("src/hooks/autopilot/__tests__/state.test.ts", "_updateQA", "updateQA"),
    ("src/hooks/autopilot/__tests__/state.test.ts", "_updateValidation", "updateValidation"),
    ("src/hooks/autopilot/__tests__/summary.test.ts", "_AutopilotState", "AutopilotState"),
    ("src/hooks/autopilot/__tests__/transition.test.ts", "_transitionToComplete", "transitionToComplete"),
    ("src/hooks/autopilot/__tests__/transitions.test.ts", "_AutopilotState", "AutopilotState"),
    ("src/hooks/autopilot/__tests__/validation.test.ts", "_AutopilotState", "AutopilotState"),
    ("src/hooks/autopilot/enforcement.ts", "_executeTransition", "executeTransition"),
    ("src/hooks/autopilot/enforcement.ts", "_TransitionStep", "TransitionStep"),
    ("src/hooks/autopilot/validation.ts", "_updateValidation", "updateValidation"),
    ("src/hooks/bridge.ts", "_TODO_CONTINUATION_PROMPT", "TODO_CONTINUATION_PROMPT"),
    ("src/hooks/keyword-detector/__tests__/index.test.ts", "_KeywordType", "KeywordType"),
    ("src/hooks/keyword-detector/__tests__/index.test.ts", "_DetectedKeyword", "DetectedKeyword"),
    ("src/hooks/learner/orchestrator.ts", "_WorkflowInsight", "WorkflowInsight"),
    ("src/hooks/mode-registry/__tests__/session-isolation.test.ts", "_canStartMode", "canStartMode"),
    ("src/hooks/mode-registry/__tests__/session-isolation.test.ts", "_getSessionStateDir", "getSessionStateDir"),
    ("src/hooks/mode-registry/__tests__/session-isolation.test.ts", "_ensureSessionStateDir", "ensureSessionStateDir"),
    ("src/hooks/mode-registry/index.ts", "_validateSessionId", "validateSessionId"),
    ("src/hooks/omc-orchestrator/index.ts", "_ALLOWED_PATH_PREFIX", "ALLOWED_PATH_PREFIX"),
    ("src/hooks/persistent-mode/__tests__/tool-error.test.ts", "_afterEach", "afterEach"),
    ("src/hooks/persistent-mode/__tests__/tool-error.test.ts", "_mkdirSync", "mkdirSync"),
    ("src/hooks/persistent-mode/__tests__/tool-error.test.ts", "_writeFileSync", "writeFileSync"),
    ("src/hooks/persistent-mode/__tests__/tool-error.test.ts", "_tmpdir", "tmpdir"),
    ("src/hooks/recovery/index.ts", "_containsTokenLimitError", "containsTokenLimitError"),
    ("src/hooks/session-end/callbacks.ts", "_normalize", "normalize"),
    ("src/hooks/session-end/callbacks.ts", "_resolve", "resolve"),
    ("src/hooks/setup/index.ts", "_dirname", "dirname"),
    ("src/hooks/subagent-tracker/__tests__/index.test.ts", "_clearTrackingState", "clearTrackingState"),
    ("src/hooks/subagent-tracker/__tests__/index.test.ts", "_TokenUsage", "TokenUsage"),
    ("src/hooks/subagent-tracker/__tests__/session-replay.test.ts", "_cleanupReplayFiles", "cleanupReplayFiles"),
    ("src/hooks/think-mode/__tests__/index.test.ts", "_beforeEach", "beforeEach"),
    ("src/hooks/think-mode/__tests__/index.test.ts", "_ThinkModeState", "ThinkModeState"),
    ("src/hooks/ultrapilot/index.ts", "_updateWorkerState", "updateWorkerState"),
    ("src/hooks/ultrapilot/index.ts", "_completeWorker", "completeWorker"),
    ("src/hooks/ultrapilot/index.ts", "_failWorker", "failWorker"),
    ("src/hooks/ultrapilot/index.ts", "_completeUltrapilot", "completeUltrapilot"),
    ("src/hud/background-cleanup.ts", "_OmcHudState", "OmcHudState"),
    ("src/hud/index.ts", "_writeFileSync", "writeFileSync"),
    ("src/hud/transcript.ts", "_SkillInvocation", "SkillInvocation"),
    ("src/hud/transcript.ts", "_ThinkingState", "ThinkingState"),
    ("src/installer/__tests__/safe-installer.test.ts", "_readFileSync", "readFileSync"),
    ("src/installer/__tests__/safe-installer.test.ts", "_install", "install"),
    ("src/interop/mcp-bridge.ts", "_updateSharedTask", "updateSharedTask"),
    ("src/interop/mcp-bridge.ts", "_SharedMessage", "SharedMessage"),
    ("src/lib/__tests__/worktree-paths.test.ts", "_mkdirSync", "mkdirSync"),
    ("src/mcp/codex-core.ts", "_existsSync", "existsSync"),
    ("src/mcp/codex-core.ts", "_dirname", "dirname"),
    ("src/mcp/codex-core.ts", "_basename", "basename"),
    ("src/mcp/gemini-core.ts", "_existsSync", "existsSync"),
    ("src/mcp/gemini-core.ts", "_dirname", "dirname"),
    ("src/mcp/gemini-core.ts", "_basename", "basename"),
    ("src/notifications/__tests__/config.test.ts", "_NotificationConfig", "NotificationConfig"),
    ("src/team/__tests__/bridge-integration.test.ts", "_resolve", "resolve"),
    ("src/team/__tests__/edge-cases.test.ts", "_getRegistrationStrategy", "getRegistrationStrategy"),
    ("src/team/__tests__/task-file-ops.test.ts", "_LockHandle", "LockHandle"),
    ("src/team/__tests__/unified-team.test.ts", "_mkdirSync", "mkdirSync"),
    ("src/team/__tests__/unified-team.test.ts", "_writeFileSync", "writeFileSync"),
    ("src/team/__tests__/unified-team.test.ts", "_homedir", "homedir"),
    ("src/team/__tests__/worker-health.test.ts", "_mkdirSync", "mkdirSync"),
    ("src/team/mcp-team-bridge.ts", "_readFileSync", "readFileSync"),
    ("src/team/mcp-team-bridge.ts", "_OutboxMessage", "OutboxMessage"),
    ("src/team/mcp-team-bridge.ts", "_readTask", "readTask"),
    ("src/team/mcp-team-bridge.ts", "_getDefaultPermissions", "getDefaultPermissions"),
    ("src/team/task-router.ts", "_UnifiedTeamMember", "UnifiedTeamMember"),
    ("src/team/team-status.ts", "_McpWorkerMember", "McpWorkerMember"),
    ("src/tools/__tests__/state-tools.test.ts", "_readFileSync", "readFileSync"),
    ("src/tools/memory-tools.ts", "_getWorktreeRoot", "getWorktreeRoot"),
    ("src/tools/memory-tools.ts", "_formatDirectivesForContext", "formatDirectivesForContext"),
    ("src/tools/memory-tools.ts", "_CustomNote", "CustomNote"),
    ("src/tools/notepad-tools.ts", "_getWorktreeRoot", "getWorktreeRoot"),
    ("src/tools/notepad-tools.ts", "_initNotepad", "initNotepad"),
    ("src/tools/notepad-tools.ts", "_readNotepad", "readNotepad"),
    ("src/tools/state-tools.ts", "_getWorktreeRoot", "getWorktreeRoot"),
    ("src/tools/state-tools.ts", "_getSessionStateDir", "getSessionStateDir"),
    ("src/tools/state-tools.ts", "_isModeActiveInAnySession", "isModeActiveInAnySession"),
    ("src/tools/trace-tools.ts", "_ReplaySummary", "ReplaySummary"),
    ("src/__tests__/analytics/token-extractor.test.ts", "_ExtractedTokens", "ExtractedTokens"),
    ("src/__tests__/analytics/token-tracker.test.ts", "_vi", "vi"),
    ("src/__tests__/analytics/transcript-parser.test.ts", "_beforeEach", "beforeEach"),
    ("src/__tests__/analytics/transcript-parser.test.ts", "_afterEach", "afterEach"),
    ("src/__tests__/analytics/transcript-scanner.test.ts", "_platform", "platform"),
    ("src/__tests__/bash-history.test.ts", "_writeFileSync", "writeFileSync"),
    ("src/__tests__/bash-history.test.ts", "_mkdirSync", "mkdirSync"),
    ("src/__tests__/bash-history.test.ts", "_homedir", "homedir"),
    ("src/__tests__/bash-history.test.ts", "_execSync", "execSync"),
    ("src/__tests__/compatibility-security.test.ts", "_resolve", "resolve"),
    ("src/__tests__/compatibility-security.test.ts", "_symlinkSync", "symlinkSync"),
    ("src/__tests__/compatibility.test.ts", "_DiscoveredPlugin", "DiscoveredPlugin"),
    ("src/__tests__/compatibility.test.ts", "_DiscoveredMcpServer", "DiscoveredMcpServer"),
    ("src/__tests__/compatibility.test.ts", "_getPluginInfo", "getPluginInfo"),
    ("src/__tests__/compatibility.test.ts", "_isPluginInstalled", "isPluginInstalled"),
    ("src/__tests__/compatibility.test.ts", "_routeCommand", "routeCommand"),
    ("src/__tests__/compatibility.test.ts", "_getExternalTool", "getExternalTool"),
    ("src/__tests__/compatibility.test.ts", "_listExternalTools", "listExternalTools"),
    ("src/__tests__/delegation-enforcement-levels.test.ts", "_afterEach", "afterEach"),
    ("src/__tests__/doctor-conflicts.test.ts", "_ConflictReport", "ConflictReport"),
    ("src/__tests__/hud-agents.test.ts", "_renderAgentsWithDescriptions", "renderAgentsWithDescriptions"),
    ("src/__tests__/hud-agents.test.ts", "_renderAgentsDescOnly", "renderAgentsDescOnly"),
    ("src/__tests__/hud/state.test.ts", "_afterEach", "afterEach"),
    ("src/__tests__/job-management.test.ts", "_afterEach", "afterEach"),
    ("src/__tests__/job-management.test.ts", "_handleListJobs", "handleListJobs"),
    ("src/__tests__/live-data.test.ts", "_afterEach", "afterEach"),
    ("src/__tests__/model-routing.test.ts", "_vi", "vi"),
    ("src/__tests__/model-routing.test.ts", "_beforeEach", "beforeEach"),
    ("src/__tests__/multi-model-mcp.test.ts", "_afterEach", "afterEach"),
    ("src/__tests__/prompt-file-only.test.ts", "_beforeEach", "beforeEach"),
    ("src/__tests__/rate-limit-wait/daemon.test.ts", "_vi", "vi"),
    ("src/__tests__/rate-limit-wait/daemon.test.ts", "_unlinkSync", "unlinkSync"),
    ("src/__tests__/rate-limit-wait/daemon.test.ts", "_statSync", "statSync"),
    ("src/__tests__/rate-limit-wait/integration.test.ts", "_writeFileSync", "writeFileSync"),
    ("src/__tests__/rate-limit-wait/integration.test.ts", "_RateLimitStatus", "RateLimitStatus"),
    ("src/__tests__/rate-limit-wait/integration.test.ts", "_BlockedPane", "BlockedPane"),
    ("src/__tests__/rate-limit-wait/tmux-detector.test.ts", "_afterEach", "afterEach"),
    ("src/__tests__/rate-limit-wait/tmux-detector.test.ts", "_scanForBlockedPanes", "scanForBlockedPanes"),
    ("src/__tests__/task-continuation.test.ts", "_TaskCheckResult", "TaskCheckResult"),
]

base = "C:/Users/ljyih/Desktop/ultrapower"
changed = 0

for rel_path, old_name, new_name in fixes:
    full_path = os.path.join(base, rel_path)
    if not os.path.exists(full_path):
        print(f"NOT FOUND: {rel_path}")
        continue
    with open(full_path, "r", encoding="utf-8") as f:
        content = f.read()
    pattern = r"\b" + re.escape(old_name) + r"\b"
    new_content = re.sub(pattern, new_name, content)
    if new_content != content:
        with open(full_path, "w", encoding="utf-8") as f:
            f.write(new_content)
        changed += 1
        print(f"FIXED: {rel_path} ({old_name} -> {new_name})")
    else:
        print(f"SKIP: {rel_path} ({old_name})")

print(f"\nDone. Files changed: {changed}")
